name: CI

env:
  PIPELINE_ORG_NAME: spring-integration-book-2
  PIPELINE_REPO_NAME: pipeline
  GH_PAT: ${{ secrets.GH_PAT }}

on:
  push:
    branches: [ master , main ]
  pull_request:
    branches: [ master , main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: ${GITHUB_WORKSPACE}/.github/workflows/trigger_book_build.sh 




